@echo off
cd /d %~dp0
set WEATHER_AUTO_TRADE_ENABLED=1
set WEATHER_ALLOW_UNAPPROVED_REPLAY_FOR_MICRO_LIVE=1
set PAPERBOT_MIN_STAKE_USD=2
set PAPERBOT_MAX_STAKE_USD=2
set WEATHER_DAILY_LIVE_LIMIT=3
set WEATHER_BUCKET_LIVE_LIMIT=2
set WEATHER_EXECUTE_TOP=1
set WEATHER_MAX_ORDERS_PER_EVENT=1
python run_auto_trade.py --live
